# Chapter 8: Recursion

<b>8.1</b>: Write a method to generate the $n^{th}$ `Fibonacci number`

`Fibonnacci` follows the sequence: 0, 1, 1, 2, 3, 5, 8, 13, 21, ....<br>
Where `fn(t) = fn(t-1) + fn(t-2)`

In [37]:
%%time 

# 1) Come up with a recursive solution
# 2) Memoize
# 3) Bottom up approach

import time

def fibonnacci_a(n):
    # brute force
    # time complexity: O(2^N)
    # space complexity: O(1)
    
    if n == 0:
        return 0
    if n == 1: 
        return 1
    
    return fibonnacci_a(n-1) + fibonnacci_a(n-2)

def fibonnacci(n):
    # time complexity: O(N)
    # space complexity: O(N)
    
    memo = {0:0, 1: 1}
    
    for i in range(2, n+1):
        memo[i] = memo[i-1] + memo[i-2]
    
    return memo[n]

fs = [fibonnacci, fibonnacci_a]

# for f in fs:
#     for i in range(60):
#         start = time.time()
#         f(i)
        
#     print(f"that took: {time.time() - start:0.3f}")

CPU times: user 7 µs, sys: 0 ns, total: 7 µs
Wall time: 10 µs


<b>8.2</b>: Imagine a robot sitting on the upper left hand corner of an `NxN` grid. The robot can only move in two directions: right and down. How many possible paths are there for the robot?

FOLLOW UP

Imagine certain squares are “off limits”, such that the robot can not step on them Design an algorithm to get all possible paths for the robot

In [268]:
import numpy as np

def num_paths_a(grid):
    # runtime: O(2^{n^2})
    # space
    n = len(grid) - 1
    
    def recurse(i, j):
        
        if i > n or j > n:
            return 0
        if i == n and j == n:
            return 1
        
        return recurse(i+1, j) + recurse(i, j+1)
    
    return recurse(0, 0)
            
    
def num_paths_b(grid):
    # runtime: O(N^2)
    n = len(grid) - 1
    m = {(n, n): 0, (n-1, n): 1, (n, n-1): 1}
        
    def recurse(i, j):

        if i > n or j > n:
            return 0
        
        if (i, j) in m:
            return m[(i, j)]
        else:
            m[(i, j)] = recurse(i+1, j) + recurse(i, j+1)
            return m[(i, j)]

    
    recurse(0, 0)

    for x, y in m:
        grid[x, y] = m[(x, y)]
        
    print(grid)
    return m[(0, 0)]
    
# def num_paths(grid):
    
#     n = len(grid) - 1
#     m = {(n, n): 0, (n-1, n): 1, (n, n-1): 1}
    
#     for 

n = 10
grid = np.zeros((4, 4))
print(grid, end="\n\n")

fs = [num_paths, num_paths_b]
     
num_paths_b(grid)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[20. 10.  4.  1.]
 [10.  6.  3.  1.]
 [ 4.  3.  2.  1.]
 [ 1.  1.  1.  0.]]


20

<b>8.3</b>: Write a method that returns all subsets of a set

In [235]:
def subset_a(s):
    n = len(s)

    def _subset(s, index):
        if len(s) == index:
            all_subsets = []
        else:
            all_subsets = _subset(s, index+1)
            
            item = s[index]
            more_subsets = []
            
            for subset  in all_subsets:
                new_subset = []
                new_subset += subset
                more_subsets.append(new_subset)
        
        return all_subsets
    return _subset(s, 0)

def subset_b(s):
    n = len(s)
    sub = [[]]
    
    for e in s:
        sub += [x+[e] for x in sub]
        
    return sub

def subset_c(s):
    sets = []

    def is_bit_set(num, bit):
        return num & (1 << bit) > 0
    for i in range(1 << len(s)):
        subset = [s[bit] for bit in range(len(s)) if is_bit_set(i, bit)]
        sets.append(subset)
    return sets

s = [1, 2, 3]

fn = [subset_b, subset_c]
sub = subset_b(s)

for f in fn:
    for i in range(20, 25):
        start = time.time()
        
        f(list(range(i)))

    print(f"that took: {time.time() - start: 0.2f}")

that took:  15.91
that took:  126.66


In [172]:
[s for bit in range(len(s))]

[[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]]

<b>8.4</b>: Write a method to compute all permutations of a string

In [265]:
import math
def permute_a(s):
    # time complexity: O(n*n!)
    # space complexity: ?
    permutations = []
    
    def recurse(d, i, size):
        if i == size:
            permutations.append("".join(d))
        else:
            
            for j in range(i, size):
                d[i], d[j] = d[j], d[i]
                recurse(d, i+1, size)
                d[i], d[j] = d[j], d[i]
                
    recurse(list(s), 0, len(s))
    return permutations

def permute_b(s):
    n = len(s)
    n_permutations = math.factorial(n)
    permutations = [[0] * n] * n_permutations
    
    j = 0
    for i in range(n_permutations):
        permutations[i][j] += 1
        j += 1
        
        if j == n:
            j = 0
            
    print(permutations)

def permute_b(string):
    permutations = []
    
    def recurse(s):
        if not s or len(s) == 0:
            return permutations
        
        if len(s) == 1:
            permutations.append(s)

        first = s[0]
        remainder = s[1:]

        words = recurse(remainder)
        
        for word in words:
            for j in range(len(word)):
                p = word[:j] + first + word[j:]
                permutations.append(p)
        return permutations
    
    return recurse(string)

s = "heya"
# permute_b(s)

In [242]:
import itertools

[ "".join(x) for x in itertools.permutations(s)]

['hey', 'hye', 'ehy', 'eyh', 'yhe', 'yeh']

<b>8.5</b>: Implement an algorithm to print all valid (e g , properly opened and closed) combinations of n-pairs of parentheses

`EXAMPLE:`
input: 3 (e g , 3 pairs of parentheses)
output: ()()(), ()(()), (())(), ((()))

<b>8.6</b>: Implement the “paint fill” function that one might see on many image editing programs. That is, given a screen (represented by a 2 dimensional array of Colors), a point, and a new color, fill in the surrounding area until you hit a border of that color

<b>8.7</b>: Given an infinite number of quarters (25 cents), dimes (10 cents), nickels (5 cents) and pennies (1 cent), write code to calculate the number of ways of representing n cents

<b>8.8</b>: Write an algorithm to print all ways of arranging eight queens on a chess board so that none of them share the same row, column or diagonal