# [Tensor Decomposition and Applications](https://www.jstor.org/stable/25662308?seq=1#metadata_info_tab_contents)
A tensor is a multidimensional N-way array. 

Two tensor decomposition methods can be considered higher order extensions of the matrix singular value decomposition (`SVD`): CANDECOMP / PARAFAC (`CP`) decomposes a tensor as a sum of rank one tensors. `Tucker decomposition` is a higher order form of principal component analysis. 

A first order tensor is a vector.<br>
A second order tensor is a matrix. <br>
Tensors of order three or higher are called higher-order tensors. <br>

In [85]:
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf

tensor = tf.linalg.diag([[1, 2, 3], [4, 5, 6]])
print("shape: ", tensor.shape)
sess = tf.Session()
print("tensor: ")
print(sess.run(tensor))

shape:  (2, 3, 3)
tensor: 
[[[1 0 0]
  [0 2 0]
  [0 0 3]]

 [[4 0 0]
  [0 5 0]
  [0 0 6]]]


## Notation
The `order` of a tensor is the number of dimensions, also known as modes. Vectors are denoted by boldface lowercase letters, matrices are denoted boldface by uppercase letters, and tensors are denoted boldface Euler script letters.

In [18]:
print("order: ", sess.run(tf.rank(tensor)))

order:  3


The higher-order analogue of matrix rows and columns, are known as `fibers`. A matrix column is a <strong>mode-1 fiber</strong> and a matrix row is a <strong>mode-2 fiber</strong>. When extracted from a tensor, fibers are assumed to be oriented as column vectors.

In [33]:
print("column vector: ", sess.run(tensor[0, :, 2]))
print("row vector: ", sess.run(tensor[0, 1, :]))

column vector:  [0 0 3]
row vector:  [0 2 0]


`slices` are two dimensional sections of a tensor, defined by fixing all but two indices. 

In [38]:
print("slice: ")
print(sess.run(tensor[0, :, :]))

slice: 
[[1 0 0]
 [0 2 0]
 [0 0 3]]


The `norm` of a tensor, is the square root sum of all of the squares of all of it's elements. 

In [40]:
print("norm: ", sess.run(tf.norm(tf.dtypes.cast(tensor, dtype=tf.float32))))

norm:  9.539392


The `inner product` of two same sized tensors $\mathscr{X}, \mathscr{Y} \in{\mathbb{R}^{I_1 x I_2 x ... x I_N}}$ is the sum of their product entries

$$<\mathscr{X}, \mathscr{Y}> = \sum_{i_1=1}^{I_1} \sum_{i_2=1}^{I_2} ... \sum_{i_N=1}^{I_N} x_{i_1 i_2 ... i_N} y_{i_1 i_2 ... i_N} $$

In [55]:
print("inner product: ", sess.run(tf.reduce_sum(tf.multiply(tensor, tensor), keep_dims=False)))

inner product:  91


### Rank-one tensors
An N-way tensor $\mathscr{X} \in{\mathbb{R}^{I_1 x I_2 x ... x I_N}}$ is `rank one` if it can be written as the `outer product` of N vectors

$$ \mathscr{X} = \textbf{a}^{(1)} \circ ~\textbf{a}^{(2)} \circ ~...~ \circ ~\textbf{a}^{(N)}$$

Where $\circ$ is the vector outer product, that is, each element of the tensor is the product of the corresponding elements of the vectors. 

### Symmetry and tensors
A tensor is called `cubical` or `symmetric` when every mode is the same size, i.e. $\mathscr{X} \in{\mathbb{R}^{I x I x ... x I}}$

### Matricization: transforming a tensor into a matrix
The process of re-ordering an N-way tensor into a matrix. 

### Matrix Kronecker, Khatri-Rao, and Hadamard Products
The `Kronecker product` of matrices looks like $A \in \mathbb{R}^{IxJ}$ and $B \in \mathbb{R}^{KxL}$ is defined by:

$A\otimes B = \begin{bmatrix} 
a_{11}B & a_{12}B & ... & a_{1J}B \\
a_{21}B & a_{22}B & ... & a_{2J}B \\
... \\
a_{I1}B & a_{I2}B & ... & a_{IJ}B \\
\end{bmatrix}
$

<br>
$A \otimes B = [a_1 \otimes b_1  ~a_1 \otimes b_2 ...  ~a_J \otimes b_{L-1} ~a_J \otimes b_L ]$

The resulting matrix is of size $(IJ) \times (KL)$

The `Khatri-Rao product` is the matching columnwise `Kronecker product`. 

$ A \odot B = [a_1 \otimes b_1  ~a_2 \otimes b_2 ...  ~a_K \otimes b_K ]$

if $\textbf{a}$ and $\textbf{b}$ are vectors, then the two are the same
$\textbf{a} \otimes \textbf{b} = \textbf{a} \odot \textbf{b} $

## Tensor Decomposition

### CP Decomposition
AKA (CANDECOMP/PARAFAC)

It's a higher order version of `SVD`. It factorizes a tensor into a sum of component rank-one tensors. For example, given a third order tensor $\mathscr{X} \in{\mathbb{R}^{I x I x ... x I}}$

$$ \mathscr{X} \approx \sum_{r=1}^R \textbf{a}_r \circ \textbf{b}_r \circ \textbf{c}_r $$